"""
This script recursively finds any '.dart' files in the ./lib directory,
and generates a 'test' file which includes all these files.

This is to ensure that *all* .dart files are included in test coverage.
By default, source files which are not touched by the unit tests are not included!

Ref: https://github.com/flutter/flutter/issues/27997#issue-410722816
"""

from pathlib import Path

if __name__ == '__main__':

    dart_files = Path('lib').rglob('*.dart')

    with open("test/test_touch_files.dart", "w") as f:

        f.write("// ignore_for_file: unused_import\n\n")

        for path in dart_files:
            path = str(path)
            # Remove leading 'lib\' text
            path = path[4:]
            path = path.replace('\\', '/')
            f.write(f'import "package:inventree/{path}";\n')

        f.write("\n\n")

        f.write("// DO NOT EDIT THIS FILE - it has been auto-generated by 'find_dart_files.py'\n")
        f.write("// It has been created to ensure that *all* source file are included in coverage data\n")
        f.write("// Reference: https://github.com/flutter/flutter/issues/27997#issue-410722816\n\n")

        f.write("// Do not actually test anything!\n")
        f.write("void main() {}\n")
