// This file is auto-generated by the 'collect_translations.py' script - do not edit it directly!

// dart format off

import "package:flutter/material.dart";

const List<Locale> supported_locales = [
    Locale("ar", "SA"),   // Translations available in app_ar_SA.arb
    Locale("bg", "BG"),   // Translations available in app_bg_BG.arb
    Locale("cs", "CZ"),   // Translations available in app_cs_CZ.arb
    Locale("da", "DK"),   // Translations available in app_da_DK.arb
    Locale("de", "DE"),   // Translations available in app_de_DE.arb
    Locale("el", "GR"),   // Translations available in app_el_GR.arb
    Locale("en", ""),   // Translations available in app_en.arb
    Locale("es", "ES"),   // Translations available in app_es_ES.arb
    Locale("es", "MX"),   // Translations available in app_es_MX.arb
    Locale("et", "EE"),   // Translations available in app_et_EE.arb
    Locale("fa", "IR"),   // Translations available in app_fa_IR.arb
    Locale("fi", "FI"),   // Translations available in app_fi_FI.arb
    Locale("fr", "FR"),   // Translations available in app_fr_FR.arb
    Locale("he", "IL"),   // Translations available in app_he_IL.arb
    Locale("hi", "IN"),   // Translations available in app_hi_IN.arb
    Locale("hu", "HU"),   // Translations available in app_hu_HU.arb
    Locale("id", "ID"),   // Translations available in app_id_ID.arb
    Locale("it", "IT"),   // Translations available in app_it_IT.arb
    Locale("ja", "JP"),   // Translations available in app_ja_JP.arb
    Locale("ko", "KR"),   // Translations available in app_ko_KR.arb
    Locale("lt", "LT"),   // Translations available in app_lt_LT.arb
    Locale("lv", "LV"),   // Translations available in app_lv_LV.arb
    Locale("nl", "NL"),   // Translations available in app_nl_NL.arb
    Locale("no", "NO"),   // Translations available in app_no_NO.arb
    Locale("pl", "PL"),   // Translations available in app_pl_PL.arb
    Locale("pt", "BR"),   // Translations available in app_pt_BR.arb
    Locale("pt", "PT"),   // Translations available in app_pt_PT.arb
    Locale("ro", "RO"),   // Translations available in app_ro_RO.arb
    Locale("ru", "RU"),   // Translations available in app_ru_RU.arb
    Locale("sk", "SK"),   // Translations available in app_sk_SK.arb
    Locale("sl", "SI"),   // Translations available in app_sl_SI.arb
    Locale("sr", "CS"),   // Translations available in app_sr_CS.arb
    Locale("sv", "SE"),   // Translations available in app_sv_SE.arb
    Locale("th", "TH"),   // Translations available in app_th_TH.arb
    Locale("tr", "TR"),   // Translations available in app_tr_TR.arb
    Locale("uk", "UA"),   // Translations available in app_uk_UA.arb
    Locale("vi", "VN"),   // Translations available in app_vi_VN.arb
    Locale("zh", "CN"),   // Translations available in app_zh_CN.arb
    Locale("zh", "TW"),   // Translations available in app_zh_TW.arb
];
